/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

import models.Diagnostic;
import models.Model;
import models.Transaction;

/**
 *
 * @author nacerkhalil
 */
public class SituationFinJournee extends javax.swing.JPanel {

    /**
     * Creates new form SituationFinJournee
     */
    
    public SituationFinJournee() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i = 0; i < model.getRowCount(); i++)
            model.removeRow(i);
        Date d = new Date(Calendar.getInstance().getTimeInMillis());
        Query q = Model.getEntityManager().createNamedQuery("transactions_today");
        q.setParameter("d", d);
        List<Transaction> list = q.getResultList();
        for(Transaction tr: list)
        {
            String[] row = new String[9];
            row[0] = (new Integer(tr.getSerial())).toString();
            row[1] = tr.getPatient().getFullName();
            row[2] = tr.getpDateDentree().toString();
            row[3] = tr.getpDateSortie().toString();
            if(tr.getAccompagnateur() != null)
            {
                row[4] = tr.getAccompagnateur().getFullName();
                row[5] = tr.getaDateDentree().toString();
                row[6] = tr.getaDateSortie().toString();
            }
            else
            {
                row[4] = "";
                row[5] = "";
                row[6] = "";
            }
            row[7] = tr.getTransactionType();
            row[8] = (new Integer(tr.getSum())).toString();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Patient", "Date d'entree", "Date de sortie", "Accompagnateur", "Date d'entree", "Date de sortie", "Type", "Somme"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
